modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"
[[mods]]
modId="arspmmo"
version="${file.jarVersion}"
displayName="ArsPMMO"
authors="Bizzoula"
description='''
PMMO Integration for Ars Nouveau
'''
[[dependencies.ArsPMMO]]
   modId="forge"
   mandatory=true
   versionRange="[36,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.ArsPMMO]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.16.5,1.17)"
   ordering="NONE"
   side="BOTH"
[[dependencies.ArsPMMO]]
   modId="arsnouveua"
   mandatory=true
   versionRange="[1.16.5,1.17)"
   ordering="NONE"
   side="BOTH"
[[dependencies.ArsPMMO]]
   modId="pmmo"
   mandatory=true
   versionRange="[1.16.5,1.17)"
   ordering="NONE"
   side="BOTH"
[[dependencies.ArsPMMO]]
   modId="geckolib3"
   mandatory=true
   versionRange="[1.16.5,1.17)"
   ordering="NONE"
   side="BOTH"
[[dependencies.ars_nouveau]]
    modId="patchouli"
    mandatory=true
    versionRange="[1.16-42,)"
    ordering="AFTER"
    side="BOTH"
